spring.application.name=global-news-engine-v1
spring.jpa.hibernate.ddl-auto=update
ingestion.raw-storage-dir=data/raw
gdelt.manifest-url=http://data.gdeltproject.org/gdeltv2/masterfilelist.txt
gdelt.manifest-tail-bytes=5242880
gdelt.ingestion.enabled=true
gdelt.ingestion.fixed-delay=PT15M
gdelt.ingestion.initial-delay=PT15M
gdelt.ingestion.max-batches-per-run=1
