spring.application.name=global-news-engine-v1
spring.jpa.hibernate.ddl-auto=update
ingestion.raw-storage-dir=data/raw
ingestion.fixed-delay=PT15M
gdelt.manifest-url=http://data.gdeltproject.org/gdeltv2/masterfilelist.txt
gdelt.manifest-tail-bytes=5242880
gdelt.ingestion.enabled=true
gdelt.discovery.minimum-batch-age=PT1H
gdelt.discovery.max-batches=3
