package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V14__create_gdelt_processing_errors extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        migrate(context.getConnection());
    }

    public void migrate(Connection connection) throws Exception {
        boolean h2 = connection.getMetaData().getDatabaseProductName().contains("H2");
        String enumConstraints = h2 ? "" : """
                    , CONSTRAINT ck_gdelt_processing_errors_dataset
                        CHECK (dataset_type IN ('EVENTS', 'MENTIONS', 'GKG'))
                    , CONSTRAINT ck_gdelt_processing_errors_failed_step
                        CHECK (failed_step IN ('PARSING', 'NORMALIZATION'))
                """;
        execute(connection, """
                CREATE TABLE gdelt_processing_errors (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dataset_type VARCHAR(16) NOT NULL,
                    source_row_id BIGINT NOT NULL,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    failed_step VARCHAR(32) NOT NULL,
                    error_code VARCHAR(64) NOT NULL,
                    error_message TEXT NOT NULL,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    resolved_at TIMESTAMP WITH TIME ZONE
                    %s,
                    CONSTRAINT ck_gdelt_processing_errors_source_row CHECK (source_row_id > 0),
                    CONSTRAINT ck_gdelt_processing_errors_row_number CHECK (row_number > 0),
                    CONSTRAINT ck_gdelt_processing_errors_resolution
                        CHECK (resolved_at IS NULL OR resolved_at >= occurred_at)
                )
                """.formatted(enumConstraints));
        execute(connection, """
                CREATE INDEX idx_gdelt_processing_errors_source
                    ON gdelt_processing_errors (dataset_type, source_row_id, resolved_at)
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_processing_errors_open
                    ON gdelt_processing_errors (resolved_at, dataset_type, error_code)
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_processing_errors_occurred
                    ON gdelt_processing_errors (occurred_at)
                """);

        long legacyCount = count(connection, "SELECT COUNT(*) FROM gdelt_stage_errors");
        execute(connection, """
                INSERT INTO gdelt_processing_errors
                    (dataset_type, source_row_id, import_file_id, source_file, source_timestamp,
                     row_number, failed_step, error_code, error_message, occurred_at, resolved_at)
                SELECT dataset_type, raw_id, import_file_id, source_file, source_timestamp,
                       row_number, 'PARSING', error_code, error_message, staged_at, NULL
                FROM gdelt_stage_errors
                ORDER BY id
                """);

        long migratedCount = count(connection, "SELECT COUNT(*) FROM gdelt_processing_errors");
        long incompleteCount = count(connection, """
                SELECT COUNT(*)
                FROM gdelt_processing_errors
                WHERE dataset_type IS NULL
                   OR source_row_id IS NULL
                   OR import_file_id IS NULL
                   OR source_file IS NULL
                   OR source_timestamp IS NULL
                   OR row_number IS NULL
                   OR failed_step IS NULL
                   OR error_code IS NULL
                   OR error_message IS NULL
                   OR occurred_at IS NULL
                """);
        if (legacyCount != migratedCount || incompleteCount != 0) {
            throw new IllegalStateException(
                    "GDELT processing error migration validation failed: legacy=%d, migrated=%d, incomplete=%d"
                            .formatted(legacyCount, migratedCount, incompleteCount));
        }

        execute(connection, "DROP TABLE gdelt_stage_errors");
    }

    private long count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
