package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V16__migrate_events_to_payload_and_domain_model extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        migrate(context.getConnection());
    }

    public void migrate(Connection connection) throws Exception {
        long rawCount = count(connection, "SELECT COUNT(*) FROM gdelt_raw_events");
        long stageCount = count(connection, "SELECT COUNT(*) FROM gdelt_stage_events");
        long signalCount = count(connection,
                "SELECT COUNT(*) FROM article_signals WHERE signal_type = 'EVENTS'");
        long extractionErrorCount = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'EVENTS'");

        execute(connection, """
                CREATE TABLE gdelt_event_payloads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    raw_tsv TEXT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT uq_gdelt_event_payloads_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_event_payloads_row_number CHECK (row_number > 0)
                )
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_event_payloads_import_file
                    ON gdelt_event_payloads (import_file_id)
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_event_payloads_source_timestamp
                    ON gdelt_event_payloads (source_timestamp)
                """);

        execute(connection, """
                CREATE TABLE gdelt_events (
                    id BIGINT PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    parsed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    global_event_id BIGINT NOT NULL,
                    event_date DATE,
                    actor1_code VARCHAR(255),
                    actor1_name TEXT,
                    actor1_country_code VARCHAR(16),
                    actor2_code VARCHAR(255),
                    actor2_name TEXT,
                    actor2_country_code VARCHAR(16),
                    event_code VARCHAR(32),
                    quad_class INTEGER,
                    goldstein_scale DOUBLE PRECISION,
                    avg_tone DOUBLE PRECISION,
                    source_url TEXT,
                    CONSTRAINT uq_gdelt_events_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_events_id CHECK (id > 0),
                    CONSTRAINT ck_gdelt_events_row_number CHECK (row_number > 0),
                    CONSTRAINT ck_gdelt_events_parsed_at CHECK (parsed_at >= ingested_at)
                )
                """);
        execute(connection, "CREATE INDEX idx_gdelt_events_import_file ON gdelt_events (import_file_id)");
        execute(connection, "CREATE INDEX idx_gdelt_events_source_timestamp ON gdelt_events (source_timestamp)");
        execute(connection, "CREATE INDEX idx_gdelt_events_global_event_id ON gdelt_events (global_event_id)");

        execute(connection, """
                INSERT INTO gdelt_event_payloads
                    (id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at)
                SELECT id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at
                FROM gdelt_raw_events
                ORDER BY id
                """);
        execute(connection, """
                INSERT INTO gdelt_events
                    (id, import_file_id, source_file, source_timestamp, row_number, ingested_at, parsed_at,
                     global_event_id, event_date, actor1_code, actor1_name, actor1_country_code,
                     actor2_code, actor2_name, actor2_country_code, event_code, quad_class,
                     goldstein_scale, avg_tone, source_url)
                SELECT raw.id, raw.import_file_id, raw.source_file, raw.source_timestamp, raw.row_number,
                       raw.ingested_at, stage.staged_at, stage.global_event_id, stage.event_date,
                       stage.actor1_code, stage.actor1_name, stage.actor1_country_code,
                       stage.actor2_code, stage.actor2_name, stage.actor2_country_code, stage.event_code,
                       stage.quad_class, stage.goldstein_scale, stage.avg_tone, stage.source_url
                FROM gdelt_stage_events stage
                JOIN gdelt_raw_events raw ON raw.id = stage.raw_id
                ORDER BY raw.id
                """);

        execute(connection, """
                UPDATE article_signals signal
                SET source_id = (
                    SELECT stage.raw_id FROM gdelt_stage_events stage WHERE stage.id = signal.source_id
                )
                WHERE signal.signal_type = 'EVENTS'
                """);
        execute(connection, """
                UPDATE article_extraction_errors error
                SET source_id = (
                    SELECT stage.raw_id FROM gdelt_stage_events stage WHERE stage.id = error.source_id
                )
                WHERE error.signal_type = 'EVENTS'
                """);

        long migratedPayloadCount = count(connection, "SELECT COUNT(*) FROM gdelt_event_payloads");
        long migratedEventCount = count(connection, "SELECT COUNT(*) FROM gdelt_events");
        long migratedSignalCount = count(connection,
                "SELECT COUNT(*) FROM article_signals WHERE signal_type = 'EVENTS'");
        long migratedExtractionErrorCount = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'EVENTS'");
        long missingEventSignals = count(connection, """
                SELECT COUNT(*)
                FROM article_signals signal
                LEFT JOIN gdelt_events event ON event.id = signal.source_id
                WHERE signal.signal_type = 'EVENTS' AND event.id IS NULL
                """);
        long missingExtractionErrors = count(connection, """
                SELECT COUNT(*)
                FROM article_extraction_errors error
                LEFT JOIN gdelt_events event ON event.id = error.source_id
                WHERE error.signal_type = 'EVENTS' AND event.id IS NULL
                """);
        if (rawCount != migratedPayloadCount
                || stageCount != migratedEventCount
                || signalCount != migratedSignalCount
                || extractionErrorCount != migratedExtractionErrorCount
                || missingEventSignals != 0
                || missingExtractionErrors != 0) {
            throw new IllegalStateException("""
                    EVENTS payload/domain migration validation failed: raw=%d, payloads=%d, stage=%d, events=%d,
                    signals=%d/%d, extractionErrors=%d/%d, missingSignalEvents=%d, missingErrorEvents=%d
                    """.formatted(rawCount, migratedPayloadCount, stageCount, migratedEventCount,
                    signalCount, migratedSignalCount, extractionErrorCount, migratedExtractionErrorCount,
                    missingEventSignals, missingExtractionErrors));
        }

        execute(connection, "DROP TABLE gdelt_stage_events");
        execute(connection, "DROP TABLE gdelt_raw_events");
        restartPayloadIdentity(connection);
    }

    private void restartPayloadIdentity(Connection connection) throws Exception {
        long nextId = count(connection, "SELECT COALESCE(MAX(id), 0) + 1 FROM gdelt_event_payloads");
        boolean h2 = connection.getMetaData().getDatabaseProductName().contains("H2");
        if (h2) {
            execute(connection, "ALTER TABLE gdelt_event_payloads ALTER COLUMN id RESTART WITH " + nextId);
        } else {
            execute(connection, "SELECT setval(pg_get_serial_sequence('gdelt_event_payloads', 'id'), "
                    + nextId + ", false)");
        }
    }

    private long count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
