package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class V17__migrate_mentions_to_payload_and_domain_model extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        migrate(context.getConnection());
    }

    public void migrate(Connection connection) throws Exception {
        long rawCount = count(connection, "SELECT COUNT(*) FROM gdelt_raw_mentions");
        long stageCount = count(connection, "SELECT COUNT(*) FROM gdelt_stage_mentions");
        long signalCount = count(connection,
                "SELECT COUNT(*) FROM article_signals WHERE signal_type = 'MENTIONS'");
        long extractionErrorCount = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'MENTIONS'");

        execute(connection, """
                CREATE TABLE gdelt_mention_payloads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    raw_tsv TEXT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT uq_gdelt_mention_payloads_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_mention_payloads_row_number CHECK (row_number > 0)
                )
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_mention_payloads_import_file
                    ON gdelt_mention_payloads (import_file_id)
                """);
        execute(connection, """
                CREATE INDEX idx_gdelt_mention_payloads_source_timestamp
                    ON gdelt_mention_payloads (source_timestamp)
                """);

        execute(connection, """
                CREATE TABLE gdelt_mentions (
                    id BIGINT PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    parsed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    global_event_id BIGINT NOT NULL,
                    event_time_date TIMESTAMP WITH TIME ZONE,
                    mention_time_date TIMESTAMP WITH TIME ZONE,
                    mention_type INTEGER,
                    mention_source_name TEXT,
                    mention_identifier TEXT,
                    confidence INTEGER,
                    mention_doc_tone DOUBLE PRECISION,
                    CONSTRAINT uq_gdelt_mentions_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_mentions_id CHECK (id > 0),
                    CONSTRAINT ck_gdelt_mentions_row_number CHECK (row_number > 0),
                    CONSTRAINT ck_gdelt_mentions_parsed_at CHECK (parsed_at >= ingested_at)
                )
                """);
        execute(connection, "CREATE INDEX idx_gdelt_mentions_import_file ON gdelt_mentions (import_file_id)");
        execute(connection, "CREATE INDEX idx_gdelt_mentions_source_timestamp ON gdelt_mentions (source_timestamp)");
        execute(connection, "CREATE INDEX idx_gdelt_mentions_global_event_id ON gdelt_mentions (global_event_id)");

        execute(connection, """
                INSERT INTO gdelt_mention_payloads
                    (id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at)
                SELECT id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at
                FROM gdelt_raw_mentions
                ORDER BY id
                """);
        execute(connection, """
                INSERT INTO gdelt_mentions
                    (id, import_file_id, source_file, source_timestamp, row_number, ingested_at, parsed_at,
                     global_event_id, event_time_date, mention_time_date, mention_type,
                     mention_source_name, mention_identifier, confidence, mention_doc_tone)
                SELECT raw.id, raw.import_file_id, raw.source_file, raw.source_timestamp, raw.row_number,
                       raw.ingested_at, stage.staged_at, stage.global_event_id, stage.event_time_date,
                       stage.mention_time_date, stage.mention_type, stage.mention_source_name,
                       stage.mention_identifier, stage.confidence, stage.mention_doc_tone
                FROM gdelt_stage_mentions stage
                JOIN gdelt_raw_mentions raw ON raw.id = stage.raw_id
                ORDER BY raw.id
                """);

        execute(connection, """
                UPDATE article_signals signal
                SET source_id = (
                    SELECT -stage.raw_id FROM gdelt_stage_mentions stage WHERE stage.id = signal.source_id
                )
                WHERE signal.signal_type = 'MENTIONS'
                """);
        execute(connection, """
                UPDATE article_signals
                SET source_id = -source_id
                WHERE signal_type = 'MENTIONS' AND source_id < 0
                """);
        execute(connection, """
                UPDATE article_extraction_errors error
                SET source_id = (
                    SELECT -stage.raw_id FROM gdelt_stage_mentions stage WHERE stage.id = error.source_id
                )
                WHERE error.signal_type = 'MENTIONS'
                """);
        execute(connection, """
                UPDATE article_extraction_errors
                SET source_id = -source_id
                WHERE signal_type = 'MENTIONS' AND source_id < 0
                """);

        long migratedPayloadCount = count(connection, "SELECT COUNT(*) FROM gdelt_mention_payloads");
        long migratedMentionCount = count(connection, "SELECT COUNT(*) FROM gdelt_mentions");
        long migratedSignalCount = count(connection,
                "SELECT COUNT(*) FROM article_signals WHERE signal_type = 'MENTIONS'");
        long migratedExtractionErrorCount = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'MENTIONS'");
        long missingMentionSignals = count(connection, """
                SELECT COUNT(*)
                FROM article_signals signal
                LEFT JOIN gdelt_mentions mention ON mention.id = signal.source_id
                WHERE signal.signal_type = 'MENTIONS' AND mention.id IS NULL
                """);
        long missingExtractionErrors = count(connection, """
                SELECT COUNT(*)
                FROM article_extraction_errors error
                LEFT JOIN gdelt_mentions mention ON mention.id = error.source_id
                WHERE error.signal_type = 'MENTIONS' AND mention.id IS NULL
                """);
        if (rawCount != migratedPayloadCount
                || stageCount != migratedMentionCount
                || signalCount != migratedSignalCount
                || extractionErrorCount != migratedExtractionErrorCount
                || missingMentionSignals != 0
                || missingExtractionErrors != 0) {
            throw new IllegalStateException("""
                    MENTIONS payload/domain migration validation failed: raw=%d, payloads=%d, stage=%d, mentions=%d,
                    signals=%d/%d, extractionErrors=%d/%d, missingSignalMentions=%d, missingErrorMentions=%d
                    """.formatted(rawCount, migratedPayloadCount, stageCount, migratedMentionCount,
                    signalCount, migratedSignalCount, extractionErrorCount, migratedExtractionErrorCount,
                    missingMentionSignals, missingExtractionErrors));
        }

        execute(connection, "DROP TABLE gdelt_stage_mentions");
        execute(connection, "DROP TABLE gdelt_raw_mentions");
        restartPayloadIdentity(connection);
    }

    private void restartPayloadIdentity(Connection connection) throws Exception {
        long nextId = count(connection, "SELECT COALESCE(MAX(id), 0) + 1 FROM gdelt_mention_payloads");
        boolean h2 = connection.getMetaData().getDatabaseProductName().contains("H2");
        if (h2) {
            execute(connection, "ALTER TABLE gdelt_mention_payloads ALTER COLUMN id RESTART WITH " + nextId);
        } else {
            execute(connection, "SELECT setval(pg_get_serial_sequence('gdelt_mention_payloads', 'id'), "
                    + nextId + ", false)");
        }
    }

    private long count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
