package db.migration;

import com.example.globalnewsenginev1.articles.normalization.GkgValueNormalizer;
import com.example.globalnewsenginev1.articles.normalization.NormalizedGkgValues;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class V18__migrate_gkg_to_payload_and_domain_model extends BaseJavaMigration {

    private final GkgValueNormalizer normalizer = new GkgValueNormalizer();
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public void migrate(Context context) throws Exception {
        migrate(context.getConnection());
    }

    public void migrate(Connection connection) throws Exception {
        long rawCount = count(connection, "SELECT COUNT(*) FROM gdelt_raw_gkg");
        long stageCount = count(connection, "SELECT COUNT(*) FROM gdelt_stage_gkg");
        long recordCount = count(connection, "SELECT COUNT(*) FROM gdelt_gkg_records");
        long extractionErrorCount = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'GKG'");
        boolean h2 = connection.getMetaData().getDatabaseProductName().contains("H2");

        execute(connection, "DROP VIEW article_detail_view");
        execute(connection, "DROP VIEW article_signal_summary_view");
        execute(connection, """
                CREATE TABLE gdelt_gkg_payloads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    raw_tsv TEXT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT uq_gdelt_gkg_payloads_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_gkg_payloads_row_number CHECK (row_number > 0)
                )
                """);
        execute(connection, "CREATE INDEX idx_gdelt_gkg_payloads_import_file ON gdelt_gkg_payloads (import_file_id)");
        execute(connection, "CREATE INDEX idx_gdelt_gkg_payloads_source_timestamp ON gdelt_gkg_payloads (source_timestamp)");
        execute(connection, """
                CREATE TABLE gdelt_gkg (
                    id BIGINT PRIMARY KEY,
                    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
                    source_file VARCHAR(255) NOT NULL,
                    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    row_number BIGINT NOT NULL,
                    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    parsed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    gkg_record_id VARCHAR(128) NOT NULL,
                    document_date TIMESTAMP WITH TIME ZONE,
                    source_collection_identifier INTEGER,
                    source_common_name TEXT,
                    document_identifier TEXT,
                    themes_raw TEXT,
                    persons_raw TEXT,
                    organizations_raw TEXT,
                    locations_raw TEXT,
                    tone_raw TEXT,
                    sharing_image_url VARCHAR(2048),
                    page_title VARCHAR(1000),
                    page_precise_pub_timestamp TIMESTAMP WITH TIME ZONE,
                    article_id BIGINT REFERENCES articles(id),
                    themes TEXT ARRAY NOT NULL,
                    persons TEXT ARRAY NOT NULL,
                    organizations TEXT ARRAY NOT NULL,
                    locations %s NOT NULL,
                    tone_value DOUBLE PRECISION,
                    tone_positive_score DOUBLE PRECISION,
                    tone_negative_score DOUBLE PRECISION,
                    tone_polarity DOUBLE PRECISION,
                    tone_activity_reference_density DOUBLE PRECISION,
                    tone_self_group_reference_density DOUBLE PRECISION,
                    tone_word_count INTEGER,
                    main_image_url VARCHAR(2048),
                    main_image_source VARCHAR(32),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT uq_gdelt_gkg_row UNIQUE (source_file, row_number),
                    CONSTRAINT ck_gdelt_gkg_id CHECK (id > 0),
                    CONSTRAINT ck_gdelt_gkg_row_number CHECK (row_number > 0),
                    CONSTRAINT ck_gdelt_gkg_parsed_at CHECK (parsed_at >= ingested_at),
                    CONSTRAINT ck_gdelt_gkg_main_image_source CHECK (
                        (main_image_url IS NULL AND main_image_source IS NULL)
                        OR (main_image_url IS NOT NULL AND main_image_source = 'GKG_SHARING_IMAGE'))
                )
                """.formatted(h2 ? "JSON" : "JSONB"));
        execute(connection, "CREATE INDEX idx_gdelt_gkg_import_file ON gdelt_gkg (import_file_id)");
        execute(connection, "CREATE INDEX idx_gdelt_gkg_source_timestamp ON gdelt_gkg (source_timestamp)");
        execute(connection, "CREATE INDEX idx_gdelt_gkg_article_id ON gdelt_gkg (article_id)");
        execute(connection, "CREATE INDEX idx_gdelt_gkg_record_id ON gdelt_gkg (gkg_record_id)");

        execute(connection, """
                INSERT INTO gdelt_gkg_payloads
                    (id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at)
                SELECT id, import_file_id, source_file, source_timestamp, row_number, raw_tsv, ingested_at
                FROM gdelt_raw_gkg
                ORDER BY id
                """);
        migrateDomainRows(connection, h2);

        execute(connection, """
                UPDATE article_extraction_errors error
                SET source_id = (
                    SELECT -stage.raw_id FROM gdelt_stage_gkg stage WHERE stage.id = error.source_id
                )
                WHERE error.signal_type = 'GKG'
                """);
        execute(connection, """
                UPDATE article_extraction_errors
                SET source_id = -source_id
                WHERE signal_type = 'GKG' AND source_id < 0
                """);

        validate(connection, rawCount, stageCount, recordCount, extractionErrorCount);
        execute(connection, "DROP TABLE gdelt_gkg_records");
        execute(connection, "DROP TABLE gdelt_stage_gkg");
        execute(connection, "DROP TABLE gdelt_raw_gkg");
        createViews(connection);
        restartPayloadIdentity(connection);
    }

    private void migrateDomainRows(Connection connection, boolean h2) throws Exception {
        String insertSql = """
                INSERT INTO gdelt_gkg
                    (id, import_file_id, source_file, source_timestamp, row_number, ingested_at, parsed_at,
                     gkg_record_id, document_date, source_collection_identifier, source_common_name,
                     document_identifier, themes_raw, persons_raw, organizations_raw, locations_raw, tone_raw,
                     sharing_image_url, page_title, page_precise_pub_timestamp, article_id,
                     themes, persons, organizations, locations, tone_value, tone_positive_score,
                     tone_negative_score, tone_polarity, tone_activity_reference_density,
                     tone_self_group_reference_density, tone_word_count, main_image_url, main_image_source,
                     created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS %s),
                        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """.formatted(h2 ? "JSON" : "JSONB");
        try (PreparedStatement select = connection.prepareStatement("""
                SELECT raw.id AS payload_id, raw.import_file_id, raw.source_file, raw.source_timestamp,
                       raw.row_number, raw.ingested_at, stage.staged_at, stage.gkg_record_id,
                       stage.document_date, stage.source_collection_identifier, stage.source_common_name,
                       stage.document_identifier, stage.themes AS themes_raw, stage.persons AS persons_raw,
                       stage.organizations AS organizations_raw, stage.locations AS locations_raw,
                       stage.tone AS tone_raw, stage.sharing_image_url, stage.page_title,
                       stage.page_precise_pub_timestamp, record.id AS product_id, record.article_id,
                       record.themes, record.persons, record.organizations,
                       CAST(record.locations AS VARCHAR) AS normalized_locations,
                       record.tone_value, record.tone_positive_score, record.tone_negative_score,
                       record.tone_polarity, record.tone_activity_reference_density,
                       record.tone_self_group_reference_density, record.tone_word_count,
                       record.main_image_url, record.main_image_source, record.created_at
                FROM gdelt_stage_gkg stage
                JOIN gdelt_raw_gkg raw ON raw.id = stage.raw_id
                LEFT JOIN gdelt_gkg_records record ON record.source_id = stage.id
                ORDER BY raw.id
                """);
             ResultSet rows = select.executeQuery();
             PreparedStatement insert = connection.prepareStatement(insertSql)) {
            while (rows.next()) {
                NormalizedGkgValues normalized = normalizer.normalize(
                        rows.getString("persons_raw"), rows.getString("organizations_raw"),
                        rows.getString("locations_raw"), rows.getString("tone_raw"));
                boolean hasProduct = rows.getObject("product_id") != null;
                String[] themes = hasProduct ? array(rows, "themes") : normalizeThemes(rows.getString("themes_raw"));
                String[] persons = hasProduct ? array(rows, "persons") : normalized.persons().toArray(String[]::new);
                String[] organizations = hasProduct
                        ? array(rows, "organizations") : normalized.organizations().toArray(String[]::new);
                String locations = hasProduct
                        ? rows.getString("normalized_locations")
                        : objectMapper.writeValueAsString(normalized.locations());

                int index = 1;
                insert.setLong(index++, rows.getLong("payload_id"));
                insert.setLong(index++, rows.getLong("import_file_id"));
                insert.setString(index++, rows.getString("source_file"));
                insert.setObject(index++, rows.getObject("source_timestamp"));
                insert.setLong(index++, rows.getLong("row_number"));
                insert.setObject(index++, rows.getObject("ingested_at"));
                insert.setObject(index++, rows.getObject("staged_at"));
                insert.setString(index++, rows.getString("gkg_record_id"));
                insert.setObject(index++, rows.getObject("document_date"));
                insert.setObject(index++, rows.getObject("source_collection_identifier"));
                insert.setString(index++, rows.getString("source_common_name"));
                insert.setString(index++, rows.getString("document_identifier"));
                insert.setString(index++, rows.getString("themes_raw"));
                insert.setString(index++, rows.getString("persons_raw"));
                insert.setString(index++, rows.getString("organizations_raw"));
                insert.setString(index++, rows.getString("locations_raw"));
                insert.setString(index++, rows.getString("tone_raw"));
                insert.setString(index++, rows.getString("sharing_image_url"));
                insert.setString(index++, rows.getString("page_title"));
                insert.setObject(index++, rows.getObject("page_precise_pub_timestamp"));
                insert.setObject(index++, hasProduct ? rows.getObject("article_id") : null);
                insert.setArray(index++, connection.createArrayOf("TEXT", themes));
                insert.setArray(index++, connection.createArrayOf("TEXT", persons));
                insert.setArray(index++, connection.createArrayOf("TEXT", organizations));
                insert.setString(index++, locations);
                insert.setObject(index++, hasProduct ? rows.getObject("tone_value") : normalized.tone().value());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_positive_score") : normalized.tone().positiveScore());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_negative_score") : normalized.tone().negativeScore());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_polarity") : normalized.tone().polarity());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_activity_reference_density") : normalized.tone().activityReferenceDensity());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_self_group_reference_density") : normalized.tone().selfGroupReferenceDensity());
                insert.setObject(index++, hasProduct ? rows.getObject("tone_word_count") : normalized.tone().wordCount());
                String imageUrl = hasProduct ? rows.getString("main_image_url") : rows.getString("sharing_image_url");
                insert.setString(index++, imageUrl);
                insert.setString(index++, hasProduct ? rows.getString("main_image_source")
                        : imageUrl == null ? null : "GKG_SHARING_IMAGE");
                insert.setObject(index, hasProduct ? rows.getObject("created_at") : rows.getObject("staged_at"));
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private void validate(Connection connection, long rawCount, long stageCount, long recordCount,
                          long extractionErrorCount) throws Exception {
        long payloadCount = count(connection, "SELECT COUNT(*) FROM gdelt_gkg_payloads");
        long domainCount = count(connection, "SELECT COUNT(*) FROM gdelt_gkg");
        long articleCount = count(connection, "SELECT COUNT(*) FROM gdelt_gkg WHERE article_id IS NOT NULL");
        long migratedExtractionErrors = count(connection,
                "SELECT COUNT(*) FROM article_extraction_errors WHERE signal_type = 'GKG'");
        long missingErrors = count(connection, """
                SELECT COUNT(*) FROM article_extraction_errors error
                LEFT JOIN gdelt_gkg gkg ON gkg.id = error.source_id
                WHERE error.signal_type = 'GKG' AND gkg.id IS NULL
                """);
        if (rawCount != payloadCount || stageCount != domainCount || recordCount != articleCount
                || extractionErrorCount != migratedExtractionErrors || missingErrors != 0) {
            throw new IllegalStateException("GKG payload/domain migration validation failed: "
                    + "raw=" + rawCount + "/" + payloadCount + ", stage=" + stageCount + "/" + domainCount
                    + ", records=" + recordCount + "/" + articleCount + ", extractionErrors="
                    + extractionErrorCount + "/" + migratedExtractionErrors + ", missingErrors=" + missingErrors);
        }
    }

    private void createViews(Connection connection) throws Exception {
        execute(connection, """
                CREATE VIEW article_signal_summary_view AS
                SELECT a.id AS article_id, a.canonical_url, a.domain, a.first_seen_at,
                       COUNT(all_signals.source_id) AS signal_count,
                       SUM(CASE WHEN all_signals.signal_type IN ('EVENT', 'EVENTS') THEN 1 ELSE 0 END) AS event_signal_count,
                       SUM(CASE WHEN all_signals.signal_type IN ('MENTION', 'MENTIONS') THEN 1 ELSE 0 END) AS mention_signal_count,
                       SUM(CASE WHEN all_signals.signal_type = 'GKG' THEN 1 ELSE 0 END) AS gkg_signal_count,
                       MIN(all_signals.source_timestamp) AS earliest_signal_at,
                       MAX(all_signals.source_timestamp) AS latest_signal_at
                FROM articles a
                LEFT JOIN (
                    SELECT article_id, signal_type, source_id, source_timestamp FROM article_signals
                    UNION ALL
                    SELECT article_id, 'GKG', id, source_timestamp FROM gdelt_gkg WHERE article_id IS NOT NULL
                ) all_signals ON all_signals.article_id = a.id
                GROUP BY a.id, a.canonical_url, a.domain, a.first_seen_at
                """);
        execute(connection, """
                CREATE VIEW article_detail_view AS
                SELECT a.id AS article_id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
                       a.created_at AS article_created_at, a.updated_at AS article_updated_at,
                       s.id AS signal_id, s.signal_type, s.source_id, s.source_timestamp,
                       s.global_event_id, s.event_code, s.themes, s.persons, s.organizations, s.locations,
                       s.tone_value, NULL AS tone_positive_score, NULL AS tone_negative_score,
                       NULL AS tone_polarity, NULL AS tone_activity_reference_density,
                       NULL AS tone_self_group_reference_density, NULL AS tone_word_count,
                       s.created_at AS signal_created_at
                FROM articles a JOIN article_signals s ON s.article_id = a.id
                UNION ALL
                SELECT a.id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
                       a.created_at, a.updated_at, g.id, 'GKG', g.id, g.source_timestamp,
                       NULL, NULL, CAST(g.themes AS VARCHAR), CAST(g.persons AS VARCHAR),
                       CAST(g.organizations AS VARCHAR), CAST(g.locations AS VARCHAR),
                       g.tone_value, g.tone_positive_score, g.tone_negative_score, g.tone_polarity,
                       g.tone_activity_reference_density, g.tone_self_group_reference_density,
                       g.tone_word_count, g.created_at
                FROM articles a JOIN gdelt_gkg g ON g.article_id = a.id
                UNION ALL
                SELECT a.id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
                       a.created_at, a.updated_at, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                       NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
                FROM articles a
                WHERE NOT EXISTS (SELECT 1 FROM article_signals s WHERE s.article_id = a.id)
                  AND NOT EXISTS (SELECT 1 FROM gdelt_gkg g WHERE g.article_id = a.id)
                """);
    }

    private String[] normalizeThemes(String raw) {
        if (raw == null || raw.isBlank()) return new String[0];
        return java.util.Arrays.stream(raw.split(";", -1)).map(String::trim).filter(value -> !value.isEmpty())
                .distinct().toArray(String[]::new);
    }

    private String[] array(ResultSet rows, String column) throws Exception {
        Array value = rows.getArray(column);
        if (value == null) return new String[0];
        Object[] source = (Object[]) value.getArray();
        return java.util.Arrays.stream(source).map(Object::toString).toArray(String[]::new);
    }

    private void restartPayloadIdentity(Connection connection) throws Exception {
        long nextId = count(connection, "SELECT COALESCE(MAX(id), 0) + 1 FROM gdelt_gkg_payloads");
        if (connection.getMetaData().getDatabaseProductName().contains("H2")) {
            execute(connection, "ALTER TABLE gdelt_gkg_payloads ALTER COLUMN id RESTART WITH " + nextId);
        } else {
            execute(connection, "SELECT setval(pg_get_serial_sequence('gdelt_gkg_payloads', 'id'), "
                    + nextId + ", false)");
        }
    }

    private long count(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }

    private void execute(Connection connection, String sql) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
