CREATE TABLE gdelt_import_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_type VARCHAR(16) NOT NULL,
    source_file VARCHAR(255) NOT NULL,
    source_url VARCHAR(1024) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    checksum_sha256 VARCHAR(64),
    status VARCHAR(16) NOT NULL,
    row_count BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    CONSTRAINT uq_gdelt_import_file UNIQUE (dataset_type, source_file)
);

CREATE TABLE gdelt_raw_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    raw_tsv TEXT NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gdelt_raw_events_row UNIQUE (source_file, row_number)
);

CREATE TABLE gdelt_raw_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    raw_tsv TEXT NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gdelt_raw_mentions_row UNIQUE (source_file, row_number)
);

CREATE TABLE gdelt_raw_gkg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    raw_tsv TEXT NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gdelt_raw_gkg_row UNIQUE (source_file, row_number)
);
