ALTER TABLE articles
    ADD CONSTRAINT uq_articles_id_url_hash UNIQUE (id, url_hash);

CREATE TABLE story_clustering_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_key VARCHAR(128) NOT NULL,
    title_normalization_version VARCHAR(128) NOT NULL,
    generic_title_rule_version VARCHAR(128) NOT NULL,
    embedding_model_id VARCHAR(128) NOT NULL,
    embedding_model_version VARCHAR(255) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    candidate_time_rule_version VARCHAR(128) NOT NULL,
    candidate_window_hours INTEGER NOT NULL,
    candidate_similarity_threshold NUMERIC(7, 6) NOT NULL,
    candidate_search_mode VARCHAR(64) NOT NULL,
    pair_decision_rule_version VARCHAR(128) NOT NULL,
    component_rule_version VARCHAR(128) NOT NULL,
    feature_normalization_versions TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_clustering_versions_key UNIQUE (version_key),
    CONSTRAINT ck_story_clustering_versions_dimension CHECK (embedding_dimension > 0),
    CONSTRAINT ck_story_clustering_versions_window CHECK (candidate_window_hours > 0),
    CONSTRAINT ck_story_clustering_versions_threshold
        CHECK (candidate_similarity_threshold >= -1 AND candidate_similarity_threshold <= 1),
    CONSTRAINT ck_story_clustering_versions_status CHECK (status IN ('SHADOW', 'ACTIVE', 'RETIRED'))
);

CREATE TABLE story_clustering_version_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    previous_status VARCHAR(16),
    new_status VARCHAR(16) NOT NULL,
    reason TEXT NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_story_clustering_status_history_previous
        CHECK (previous_status IS NULL OR previous_status IN ('SHADOW', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_story_clustering_status_history_new
        CHECK (new_status IN ('SHADOW', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_story_clustering_status_history_transition CHECK (
        (previous_status IS NULL AND new_status = 'SHADOW')
        OR (previous_status = 'SHADOW' AND new_status = 'ACTIVE')
        OR (previous_status = 'ACTIVE' AND new_status = 'RETIRED')
        OR (previous_status = 'RETIRED' AND new_status = 'ACTIVE')
    )
);

CREATE TABLE story_embedding_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_model_id VARCHAR(128) NOT NULL,
    embedding_model_version VARCHAR(255) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    title_normalization_version VARCHAR(128) NOT NULL,
    title_input_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    vector_bytes BYTEA,
    vector_hash VARCHAR(64),
    vector_norm NUMERIC(20, 10),
    provider_request_id VARCHAR(255),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    ready_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_embedding_artifacts_key UNIQUE (
        embedding_model_id,
        embedding_model_version,
        embedding_dimension,
        title_normalization_version,
        title_input_hash
    ),
    CONSTRAINT uq_story_embedding_artifacts_id_hash UNIQUE (id, vector_hash),
    CONSTRAINT ck_story_embedding_artifacts_dimension CHECK (embedding_dimension > 0),
    CONSTRAINT ck_story_embedding_artifacts_title_hash CHECK (CHAR_LENGTH(title_input_hash) = 64),
    CONSTRAINT ck_story_embedding_artifacts_status
        CHECK (status IN ('PENDING', 'READY', 'RETRYABLE_FAILURE', 'TERMINAL_FAILURE')),
    CONSTRAINT ck_story_embedding_artifacts_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_story_embedding_artifacts_payload CHECK (
        (status = 'READY'
            AND vector_bytes IS NOT NULL
            AND OCTET_LENGTH(vector_bytes) = embedding_dimension * 4
            AND vector_hash IS NOT NULL
            AND CHAR_LENGTH(vector_hash) = 64
            AND vector_norm > 0
            AND ready_at IS NOT NULL
            AND next_retry_at IS NULL)
        OR (status <> 'READY'
            AND vector_bytes IS NULL
            AND vector_hash IS NULL
            AND vector_norm IS NULL
            AND ready_at IS NULL)
    ),
    CONSTRAINT ck_story_embedding_artifacts_retry CHECK (
        status = 'RETRYABLE_FAILURE' OR next_retry_at IS NULL
    )
);

CREATE TABLE story_embedding_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_artifact_id BIGINT NOT NULL REFERENCES story_embedding_artifacts(id),
    attempt_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_request_id VARCHAR(255),
    error_code VARCHAR(128),
    error_message TEXT,
    observed_dimension INTEGER,
    observed_vector_hash VARCHAR(64),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_story_embedding_attempts_number UNIQUE (embedding_artifact_id, attempt_number),
    CONSTRAINT ck_story_embedding_attempts_number CHECK (attempt_number > 0),
    CONSTRAINT ck_story_embedding_attempts_status
        CHECK (status IN ('PENDING', 'READY', 'RETRYABLE_FAILURE', 'TERMINAL_FAILURE', 'MODEL_DRIFT')),
    CONSTRAINT ck_story_embedding_attempts_dimension
        CHECK (observed_dimension IS NULL OR observed_dimension > 0),
    CONSTRAINT ck_story_embedding_attempts_hash
        CHECK (observed_vector_hash IS NULL OR CHAR_LENGTH(observed_vector_hash) = 64)
);

CREATE TABLE story_article_inputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    article_id BIGINT NOT NULL,
    article_ref VARCHAR(64) NOT NULL,
    effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    effective_at_source VARCHAR(32) NOT NULL,
    normalized_title TEXT,
    title_input_hash VARCHAR(64),
    title_usability VARCHAR(32) NOT NULL,
    article_input_fingerprint VARCHAR(64) NOT NULL,
    embedding_status VARCHAR(32) NOT NULL,
    embedding_artifact_id BIGINT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    current_marker SMALLINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    superseded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_story_article_inputs_article
        FOREIGN KEY (article_id, article_ref) REFERENCES articles(id, url_hash),
    CONSTRAINT fk_story_article_inputs_embedding
        FOREIGN KEY (embedding_artifact_id) REFERENCES story_embedding_artifacts(id),
    CONSTRAINT uq_story_article_inputs_fingerprint
        UNIQUE (clustering_version_id, article_ref, article_input_fingerprint),
    CONSTRAINT uq_story_article_inputs_current
        UNIQUE (clustering_version_id, article_ref, current_marker),
    CONSTRAINT uq_story_article_inputs_id_version
        UNIQUE (id, clustering_version_id),
    CONSTRAINT uq_story_article_inputs_snapshot_ref
        UNIQUE (id, clustering_version_id, article_ref, article_input_fingerprint),
    CONSTRAINT ck_story_article_inputs_time_source
        CHECK (effective_at_source IN ('PUBLISHED_AT', 'FIRST_SEEN_AT')),
    CONSTRAINT ck_story_article_inputs_title_hash
        CHECK (title_input_hash IS NULL OR CHAR_LENGTH(title_input_hash) = 64),
    CONSTRAINT ck_story_article_inputs_fingerprint
        CHECK (CHAR_LENGTH(article_input_fingerprint) = 64),
    CONSTRAINT ck_story_article_inputs_title_usability
        CHECK (title_usability IN ('USABLE', 'TITLE_MISSING', 'TITLE_GENERIC')),
    CONSTRAINT ck_story_article_inputs_embedding_status CHECK (
        embedding_status IN (
            'NOT_REQUIRED', 'PENDING', 'READY', 'RETRYABLE_FAILURE', 'TERMINAL_FAILURE'
        )
    ),
    CONSTRAINT ck_story_article_inputs_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_story_article_inputs_current CHECK (
        (current_marker = 1 AND superseded_at IS NULL)
        OR (current_marker IS NULL AND superseded_at IS NOT NULL)
    ),
    CONSTRAINT ck_story_article_inputs_title_payload CHECK (
        (title_usability = 'USABLE'
            AND normalized_title IS NOT NULL
            AND title_input_hash IS NOT NULL
            AND embedding_status <> 'NOT_REQUIRED')
        OR (title_usability IN ('TITLE_MISSING', 'TITLE_GENERIC')
            AND title_input_hash IS NULL
            AND embedding_status = 'NOT_REQUIRED'
            AND embedding_artifact_id IS NULL)
    ),
    CONSTRAINT ck_story_article_inputs_embedding_payload CHECK (
        (embedding_status = 'READY' AND embedding_artifact_id IS NOT NULL AND next_retry_at IS NULL)
        OR (embedding_status = 'RETRYABLE_FAILURE' AND embedding_artifact_id IS NOT NULL)
        OR (embedding_status IN ('PENDING', 'TERMINAL_FAILURE')
            AND embedding_artifact_id IS NOT NULL
            AND next_retry_at IS NULL)
        OR (embedding_status = 'NOT_REQUIRED'
            AND embedding_artifact_id IS NULL
            AND next_retry_at IS NULL)
    )
);

CREATE TABLE story_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    snapshot_key VARCHAR(64) NOT NULL,
    snapshot_watermark TIMESTAMP WITH TIME ZONE NOT NULL,
    snapshot_input_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_snapshots_key UNIQUE (clustering_version_id, snapshot_key),
    CONSTRAINT uq_story_snapshots_input UNIQUE (clustering_version_id, snapshot_input_hash),
    CONSTRAINT uq_story_snapshots_id_version UNIQUE (id, clustering_version_id),
    CONSTRAINT ck_story_snapshots_key CHECK (CHAR_LENGTH(snapshot_key) = 64),
    CONSTRAINT ck_story_snapshots_input_hash CHECK (CHAR_LENGTH(snapshot_input_hash) = 64)
);

CREATE TABLE story_snapshot_members (
    snapshot_id BIGINT NOT NULL,
    clustering_version_id BIGINT NOT NULL,
    article_input_id BIGINT NOT NULL,
    article_ref VARCHAR(64) NOT NULL,
    article_input_fingerprint VARCHAR(64) NOT NULL,
    embedding_artifact_id BIGINT,
    vector_hash VARCHAR(64),
    PRIMARY KEY (snapshot_id, article_input_id),
    CONSTRAINT fk_story_snapshot_members_snapshot
        FOREIGN KEY (snapshot_id, clustering_version_id)
        REFERENCES story_snapshots(id, clustering_version_id),
    CONSTRAINT fk_story_snapshot_members_input
        FOREIGN KEY (
            article_input_id,
            clustering_version_id,
            article_ref,
            article_input_fingerprint
        )
        REFERENCES story_article_inputs (
            id,
            clustering_version_id,
            article_ref,
            article_input_fingerprint
        ),
    CONSTRAINT fk_story_snapshot_members_embedding
        FOREIGN KEY (embedding_artifact_id, vector_hash)
        REFERENCES story_embedding_artifacts(id, vector_hash),
    CONSTRAINT uq_story_snapshot_members_article UNIQUE (snapshot_id, article_ref),
    CONSTRAINT ck_story_snapshot_members_fingerprint
        CHECK (CHAR_LENGTH(article_input_fingerprint) = 64),
    CONSTRAINT ck_story_snapshot_members_vector_hash
        CHECK (vector_hash IS NULL OR CHAR_LENGTH(vector_hash) = 64),
    CONSTRAINT ck_story_snapshot_members_embedding CHECK (
        (embedding_artifact_id IS NULL AND vector_hash IS NULL)
        OR (embedding_artifact_id IS NOT NULL AND vector_hash IS NOT NULL)
    )
);

CREATE TABLE story_processing_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key VARCHAR(64) NOT NULL,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    snapshot_id BIGINT NOT NULL,
    run_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    fencing_token BIGINT NOT NULL,
    retry_of_run_id BIGINT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    read_article_count BIGINT NOT NULL DEFAULT 0,
    changed_article_count BIGINT NOT NULL DEFAULT 0,
    skipped_article_count BIGINT NOT NULL DEFAULT 0,
    failed_article_count BIGINT NOT NULL DEFAULT 0,
    candidate_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_story_processing_runs_key UNIQUE (run_key),
    CONSTRAINT uq_story_processing_runs_fencing UNIQUE (clustering_version_id, fencing_token),
    CONSTRAINT uq_story_processing_runs_id_version UNIQUE (id, clustering_version_id),
    CONSTRAINT fk_story_processing_runs_snapshot
        FOREIGN KEY (snapshot_id, clustering_version_id)
        REFERENCES story_snapshots(id, clustering_version_id),
    CONSTRAINT fk_story_processing_runs_retry
        FOREIGN KEY (retry_of_run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT ck_story_processing_runs_key CHECK (CHAR_LENGTH(run_key) = 64),
    CONSTRAINT ck_story_processing_runs_mode
        CHECK (run_mode IN ('INCREMENTAL', 'BACKFILL', 'REPROCESSING')),
    CONSTRAINT ck_story_processing_runs_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DISCARDED')),
    CONSTRAINT ck_story_processing_runs_fencing CHECK (fencing_token >= 0),
    CONSTRAINT ck_story_processing_runs_counts CHECK (
        read_article_count >= 0
        AND changed_article_count >= 0
        AND skipped_article_count >= 0
        AND failed_article_count >= 0
        AND candidate_count >= 0
    ),
    CONSTRAINT ck_story_processing_runs_completion CHECK (
        (status IN ('PENDING', 'RUNNING') AND completed_at IS NULL)
        OR (status IN ('SUCCEEDED', 'FAILED', 'DISCARDED') AND completed_at IS NOT NULL)
    )
);

CREATE TABLE stories (
    id UUID PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    identity_anchor_article_ref VARCHAR(64) NOT NULL REFERENCES articles(url_hash),
    representative_article_ref VARCHAR(64) NOT NULL REFERENCES articles(url_hash),
    state VARCHAR(16) NOT NULL,
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    effective_to TIMESTAMP WITH TIME ZONE NOT NULL,
    optimistic_version BIGINT NOT NULL DEFAULT 0,
    created_by_run_id BIGINT NOT NULL,
    last_changed_by_run_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    superseded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_stories_id_version UNIQUE (id, clustering_version_id),
    CONSTRAINT fk_stories_created_run
        FOREIGN KEY (created_by_run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT fk_stories_changed_run
        FOREIGN KEY (last_changed_by_run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT ck_stories_state CHECK (state IN ('ACTIVE', 'CLOSED', 'SUPERSEDED')),
    CONSTRAINT ck_stories_effective_range CHECK (effective_from <= effective_to),
    CONSTRAINT ck_stories_optimistic_version CHECK (optimistic_version >= 0),
    CONSTRAINT ck_stories_state_timestamps CHECK (
        (state = 'ACTIVE' AND closed_at IS NULL AND superseded_at IS NULL)
        OR (state = 'CLOSED' AND closed_at IS NOT NULL AND superseded_at IS NULL)
        OR (state = 'SUPERSEDED' AND superseded_at IS NOT NULL)
    )
);

CREATE TABLE story_pair_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_hash VARCHAR(64) NOT NULL,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    run_id BIGINT NOT NULL,
    snapshot_id BIGINT NOT NULL,
    left_article_input_id BIGINT NOT NULL,
    right_article_input_id BIGINT NOT NULL,
    left_article_ref VARCHAR(64) NOT NULL,
    right_article_ref VARCHAR(64) NOT NULL,
    left_article_input_fingerprint VARCHAR(64) NOT NULL,
    right_article_input_fingerprint VARCHAR(64) NOT NULL,
    left_effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    right_effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    left_effective_at_source VARCHAR(32) NOT NULL,
    right_effective_at_source VARCHAR(32) NOT NULL,
    left_title_input_hash VARCHAR(64) NOT NULL,
    right_title_input_hash VARCHAR(64) NOT NULL,
    left_embedding_artifact_id BIGINT NOT NULL,
    right_embedding_artifact_id BIGINT NOT NULL,
    left_vector_hash VARCHAR(64) NOT NULL,
    right_vector_hash VARCHAR(64) NOT NULL,
    cosine_similarity NUMERIC(7, 6) NOT NULL,
    time_distance_seconds BIGINT NOT NULL,
    candidate_rank INTEGER,
    candidate_window_hours INTEGER NOT NULL,
    similarity_threshold NUMERIC(7, 6) NOT NULL,
    pair_rule_version VARCHAR(128) NOT NULL,
    result VARCHAR(32) NOT NULL,
    triggered_rule VARCHAR(128) NOT NULL,
    top_one_below_threshold BOOLEAN NOT NULL DEFAULT FALSE,
    non_decisive_evidence TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_pair_decisions_hash UNIQUE (decision_hash),
    CONSTRAINT uq_story_pair_decisions_pair
        UNIQUE (snapshot_id, left_article_ref, right_article_ref, pair_rule_version),
    CONSTRAINT fk_story_pair_decisions_run
        FOREIGN KEY (run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT fk_story_pair_decisions_snapshot
        FOREIGN KEY (snapshot_id, clustering_version_id)
        REFERENCES story_snapshots(id, clustering_version_id),
    CONSTRAINT fk_story_pair_decisions_left_input
        FOREIGN KEY (left_article_input_id, clustering_version_id)
        REFERENCES story_article_inputs(id, clustering_version_id),
    CONSTRAINT fk_story_pair_decisions_right_input
        FOREIGN KEY (right_article_input_id, clustering_version_id)
        REFERENCES story_article_inputs(id, clustering_version_id),
    CONSTRAINT fk_story_pair_decisions_left_snapshot_member
        FOREIGN KEY (snapshot_id, left_article_input_id)
        REFERENCES story_snapshot_members(snapshot_id, article_input_id),
    CONSTRAINT fk_story_pair_decisions_right_snapshot_member
        FOREIGN KEY (snapshot_id, right_article_input_id)
        REFERENCES story_snapshot_members(snapshot_id, article_input_id),
    CONSTRAINT fk_story_pair_decisions_left_embedding
        FOREIGN KEY (left_embedding_artifact_id, left_vector_hash)
        REFERENCES story_embedding_artifacts(id, vector_hash),
    CONSTRAINT fk_story_pair_decisions_right_embedding
        FOREIGN KEY (right_embedding_artifact_id, right_vector_hash)
        REFERENCES story_embedding_artifacts(id, vector_hash),
    CONSTRAINT ck_story_pair_decisions_hash CHECK (CHAR_LENGTH(decision_hash) = 64),
    CONSTRAINT ck_story_pair_decisions_order CHECK (left_article_ref < right_article_ref),
    CONSTRAINT ck_story_pair_decisions_fingerprints CHECK (
        CHAR_LENGTH(left_article_input_fingerprint) = 64
        AND CHAR_LENGTH(right_article_input_fingerprint) = 64
    ),
    CONSTRAINT ck_story_pair_decisions_title_hashes CHECK (
        CHAR_LENGTH(left_title_input_hash) = 64
        AND CHAR_LENGTH(right_title_input_hash) = 64
    ),
    CONSTRAINT ck_story_pair_decisions_vector_hashes CHECK (
        CHAR_LENGTH(left_vector_hash) = 64
        AND CHAR_LENGTH(right_vector_hash) = 64
    ),
    CONSTRAINT ck_story_pair_decisions_similarity
        CHECK (cosine_similarity >= -1 AND cosine_similarity <= 1),
    CONSTRAINT ck_story_pair_decisions_time CHECK (time_distance_seconds >= 0),
    CONSTRAINT ck_story_pair_decisions_rank CHECK (candidate_rank IS NULL OR candidate_rank > 0),
    CONSTRAINT ck_story_pair_decisions_window CHECK (candidate_window_hours > 0),
    CONSTRAINT ck_story_pair_decisions_threshold
        CHECK (similarity_threshold >= -1 AND similarity_threshold <= 1),
    CONSTRAINT ck_story_pair_decisions_result CHECK (result IN ('SAME_STORY', 'UNCERTAIN')),
    CONSTRAINT ck_story_pair_decisions_sources CHECK (
        left_effective_at_source IN ('PUBLISHED_AT', 'FIRST_SEEN_AT')
        AND right_effective_at_source IN ('PUBLISHED_AT', 'FIRST_SEEN_AT')
    ),
    CONSTRAINT ck_story_pair_decisions_top_one CHECK (
        NOT top_one_below_threshold OR result = 'UNCERTAIN'
    )
);

CREATE TABLE story_assignment_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_hash VARCHAR(64) NOT NULL,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    run_id BIGINT NOT NULL,
    snapshot_id BIGINT NOT NULL,
    article_input_id BIGINT NOT NULL,
    article_ref VARCHAR(64) NOT NULL,
    article_input_fingerprint VARCHAR(64) NOT NULL,
    previous_story_id UUID,
    resulting_story_id UUID,
    result VARCHAR(32) NOT NULL,
    assignment_reason VARCHAR(128) NOT NULL,
    component_rule_version VARCHAR(128) NOT NULL,
    best_comparison_article_ref VARCHAR(64),
    best_cosine_similarity NUMERIC(7, 6),
    non_decisive_evidence TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_assignment_decisions_hash UNIQUE (decision_hash),
    CONSTRAINT uq_story_assignment_decisions_input
        UNIQUE (clustering_version_id, article_ref, article_input_fingerprint),
    CONSTRAINT uq_story_assignment_decisions_id_version
        UNIQUE (id, clustering_version_id),
    CONSTRAINT fk_story_assignment_decisions_run
        FOREIGN KEY (run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT fk_story_assignment_decisions_snapshot
        FOREIGN KEY (snapshot_id, clustering_version_id)
        REFERENCES story_snapshots(id, clustering_version_id),
    CONSTRAINT fk_story_assignment_decisions_input
        FOREIGN KEY (article_input_id, clustering_version_id)
        REFERENCES story_article_inputs(id, clustering_version_id),
    CONSTRAINT fk_story_assignment_decisions_snapshot_member
        FOREIGN KEY (snapshot_id, article_input_id)
        REFERENCES story_snapshot_members(snapshot_id, article_input_id),
    CONSTRAINT fk_story_assignment_decisions_previous_story
        FOREIGN KEY (previous_story_id, clustering_version_id)
        REFERENCES stories(id, clustering_version_id),
    CONSTRAINT fk_story_assignment_decisions_resulting_story
        FOREIGN KEY (resulting_story_id, clustering_version_id)
        REFERENCES stories(id, clustering_version_id),
    CONSTRAINT ck_story_assignment_decisions_hash CHECK (CHAR_LENGTH(decision_hash) = 64),
    CONSTRAINT ck_story_assignment_decisions_input_fingerprint
        CHECK (CHAR_LENGTH(article_input_fingerprint) = 64),
    CONSTRAINT ck_story_assignment_decisions_result
        CHECK (result IN ('ASSIGNED', 'UNASSIGNED', 'NO_CHANGE')),
    CONSTRAINT ck_story_assignment_decisions_story CHECK (
        (result = 'ASSIGNED' AND resulting_story_id IS NOT NULL)
        OR (result = 'UNASSIGNED' AND resulting_story_id IS NULL)
        OR result = 'NO_CHANGE'
    ),
    CONSTRAINT ck_story_assignment_decisions_similarity
        CHECK (best_cosine_similarity IS NULL
            OR (best_cosine_similarity >= -1 AND best_cosine_similarity <= 1))
);

CREATE TABLE story_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id UUID NOT NULL,
    clustering_version_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    article_ref VARCHAR(64) NOT NULL,
    article_input_fingerprint VARCHAR(64) NOT NULL,
    valid_from_run_id BIGINT NOT NULL,
    valid_to_run_id BIGINT,
    decision_id BIGINT NOT NULL,
    assignment_reason VARCHAR(128) NOT NULL,
    current_marker SMALLINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_story_memberships_story
        FOREIGN KEY (story_id, clustering_version_id) REFERENCES stories(id, clustering_version_id),
    CONSTRAINT fk_story_memberships_article
        FOREIGN KEY (article_id, article_ref) REFERENCES articles(id, url_hash),
    CONSTRAINT fk_story_memberships_from_run
        FOREIGN KEY (valid_from_run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT fk_story_memberships_to_run
        FOREIGN KEY (valid_to_run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT fk_story_memberships_decision
        FOREIGN KEY (decision_id, clustering_version_id)
        REFERENCES story_assignment_decisions(id, clustering_version_id),
    CONSTRAINT uq_story_memberships_current
        UNIQUE (clustering_version_id, article_ref, current_marker),
    CONSTRAINT uq_story_memberships_interval
        UNIQUE (clustering_version_id, article_ref, valid_from_run_id),
    CONSTRAINT ck_story_memberships_fingerprint
        CHECK (CHAR_LENGTH(article_input_fingerprint) = 64),
    CONSTRAINT ck_story_memberships_current CHECK (
        (current_marker = 1 AND valid_to_run_id IS NULL AND ended_at IS NULL)
        OR (current_marker IS NULL AND valid_to_run_id IS NOT NULL AND ended_at IS NOT NULL)
    ),
    CONSTRAINT ck_story_memberships_interval CHECK (
        valid_to_run_id IS NULL OR valid_to_run_id <> valid_from_run_id
    )
);

CREATE TABLE story_lineage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL,
    predecessor_story_id UUID NOT NULL,
    successor_story_id UUID NOT NULL,
    run_id BIGINT NOT NULL,
    reason VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_story_lineage_predecessor
        FOREIGN KEY (predecessor_story_id, clustering_version_id)
        REFERENCES stories(id, clustering_version_id),
    CONSTRAINT fk_story_lineage_successor
        FOREIGN KEY (successor_story_id, clustering_version_id)
        REFERENCES stories(id, clustering_version_id),
    CONSTRAINT fk_story_lineage_run
        FOREIGN KEY (run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT uq_story_lineage_edge
        UNIQUE (clustering_version_id, predecessor_story_id, successor_story_id, run_id),
    CONSTRAINT ck_story_lineage_distinct CHECK (predecessor_story_id <> successor_story_id),
    CONSTRAINT ck_story_lineage_reason CHECK (reason IN ('MERGE', 'SPLIT', 'REPROCESSING'))
);

CREATE TABLE story_state_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clustering_version_id BIGINT NOT NULL,
    story_id UUID NOT NULL,
    run_id BIGINT NOT NULL,
    previous_state VARCHAR(16),
    new_state VARCHAR(16) NOT NULL,
    reason VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_story_state_changes_story
        FOREIGN KEY (story_id, clustering_version_id) REFERENCES stories(id, clustering_version_id),
    CONSTRAINT fk_story_state_changes_run
        FOREIGN KEY (run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT uq_story_state_changes_run UNIQUE (story_id, run_id, new_state),
    CONSTRAINT ck_story_state_changes_previous
        CHECK (previous_state IS NULL OR previous_state IN ('ACTIVE', 'CLOSED', 'SUPERSEDED')),
    CONSTRAINT ck_story_state_changes_new
        CHECK (new_state IN ('ACTIVE', 'CLOSED', 'SUPERSEDED')),
    CONSTRAINT ck_story_state_changes_transition CHECK (
        (previous_state IS NULL AND new_state = 'ACTIVE')
        OR (previous_state = 'ACTIVE' AND new_state IN ('CLOSED', 'SUPERSEDED'))
        OR (previous_state = 'CLOSED' AND new_state IN ('ACTIVE', 'SUPERSEDED'))
    )
);

CREATE TABLE story_publish_commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_key VARCHAR(64) NOT NULL,
    clustering_version_id BIGINT NOT NULL REFERENCES story_clustering_versions(id),
    snapshot_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    fencing_token BIGINT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_story_publish_commits_key UNIQUE (clustering_version_id, publish_key),
    CONSTRAINT uq_story_publish_commits_snapshot UNIQUE (clustering_version_id, snapshot_id),
    CONSTRAINT uq_story_publish_commits_run UNIQUE (run_id),
    CONSTRAINT fk_story_publish_commits_snapshot
        FOREIGN KEY (snapshot_id, clustering_version_id)
        REFERENCES story_snapshots(id, clustering_version_id),
    CONSTRAINT fk_story_publish_commits_run
        FOREIGN KEY (run_id, clustering_version_id)
        REFERENCES story_processing_runs(id, clustering_version_id),
    CONSTRAINT ck_story_publish_commits_key CHECK (CHAR_LENGTH(publish_key) = 64),
    CONSTRAINT ck_story_publish_commits_fencing CHECK (fencing_token >= 0)
);

CREATE INDEX idx_story_clustering_versions_status
    ON story_clustering_versions (status);
CREATE INDEX idx_story_clustering_status_history_version
    ON story_clustering_version_status_history (clustering_version_id, changed_at);
CREATE INDEX idx_story_embedding_artifacts_status_retry
    ON story_embedding_artifacts (status, next_retry_at);
CREATE INDEX idx_story_embedding_attempts_artifact
    ON story_embedding_attempts (embedding_artifact_id, attempt_number);
CREATE INDEX idx_story_article_inputs_article
    ON story_article_inputs (article_ref, clustering_version_id);
CREATE INDEX idx_story_article_inputs_effective_at
    ON story_article_inputs (clustering_version_id, effective_at);
CREATE INDEX idx_story_article_inputs_status_retry
    ON story_article_inputs (embedding_status, next_retry_at);
CREATE INDEX idx_story_snapshot_members_embedding
    ON story_snapshot_members (embedding_artifact_id);
CREATE INDEX idx_story_processing_runs_status
    ON story_processing_runs (clustering_version_id, status, started_at);
CREATE INDEX idx_stories_version_state
    ON stories (clustering_version_id, state, effective_to);
CREATE INDEX idx_stories_anchor
    ON stories (identity_anchor_article_ref);
CREATE INDEX idx_story_pair_decisions_run
    ON story_pair_decisions (run_id, result);
CREATE INDEX idx_story_pair_decisions_left
    ON story_pair_decisions (left_article_ref, created_at);
CREATE INDEX idx_story_pair_decisions_right
    ON story_pair_decisions (right_article_ref, created_at);
CREATE INDEX idx_story_assignment_decisions_run
    ON story_assignment_decisions (run_id, result);
CREATE INDEX idx_story_assignment_decisions_article
    ON story_assignment_decisions (article_ref, clustering_version_id);
CREATE INDEX idx_story_memberships_story
    ON story_memberships (story_id, current_marker);
CREATE INDEX idx_story_memberships_article
    ON story_memberships (article_ref, clustering_version_id);
CREATE INDEX idx_story_lineage_predecessor
    ON story_lineage (predecessor_story_id);
CREATE INDEX idx_story_lineage_successor
    ON story_lineage (successor_story_id);
CREATE INDEX idx_story_state_changes_story
    ON story_state_changes (story_id, created_at);

INSERT INTO story_clustering_versions (
    version_key,
    title_normalization_version,
    generic_title_rule_version,
    embedding_model_id,
    embedding_model_version,
    embedding_dimension,
    candidate_time_rule_version,
    candidate_window_hours,
    candidate_similarity_threshold,
    candidate_search_mode,
    pair_decision_rule_version,
    component_rule_version,
    feature_normalization_versions,
    status,
    created_at,
    updated_at
) VALUES
    (
        'story-mvp-title-embedding-24h-v1.0.0',
        'art031-title-nfkc-ws-v1',
        'art031-generic-title-v1',
        'text-embedding-3-small',
        'openai:text-embedding-3-small@2026-07-20',
        1536,
        'published-at-else-first-seen-v1',
        24,
        0.700000,
        'exact-cosine-radius-v1',
        'cosine-070-time24-v1',
        'medoid-radius-agglomerative-v1',
        'none-v1',
        'SHADOW',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'story-mvp-title-embedding-48h-v1.0.0',
        'art031-title-nfkc-ws-v1',
        'art031-generic-title-v1',
        'text-embedding-3-small',
        'openai:text-embedding-3-small@2026-07-20',
        1536,
        'published-at-else-first-seen-v1',
        48,
        0.700000,
        'exact-cosine-radius-v1',
        'cosine-070-time48-v1',
        'medoid-radius-agglomerative-v1',
        'none-v1',
        'SHADOW',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'story-mvp-title-embedding-72h-v1.0.0',
        'art031-title-nfkc-ws-v1',
        'art031-generic-title-v1',
        'text-embedding-3-small',
        'openai:text-embedding-3-small@2026-07-20',
        1536,
        'published-at-else-first-seen-v1',
        72,
        0.700000,
        'exact-cosine-radius-v1',
        'cosine-070-time72-v1',
        'medoid-radius-agglomerative-v1',
        'none-v1',
        'SHADOW',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

INSERT INTO story_clustering_version_status_history (
    clustering_version_id,
    previous_status,
    new_status,
    reason,
    changed_at
)
SELECT id, NULL, 'SHADOW', 'Initial ART-034 schema seed', created_at
FROM story_clustering_versions;
