CREATE TABLE gdelt_stage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_id BIGINT NOT NULL REFERENCES gdelt_raw_events(id),
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    staged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    global_event_id BIGINT NOT NULL,
    event_date DATE,
    actor1_code VARCHAR(255),
    actor1_name TEXT,
    actor1_country_code VARCHAR(16),
    actor2_code VARCHAR(255),
    actor2_name TEXT,
    actor2_country_code VARCHAR(16),
    event_code VARCHAR(32),
    quad_class INTEGER,
    goldstein_scale DOUBLE PRECISION,
    avg_tone DOUBLE PRECISION,
    source_url TEXT,
    CONSTRAINT uq_gdelt_stage_events_raw UNIQUE (raw_id)
);

CREATE TABLE gdelt_stage_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_id BIGINT NOT NULL REFERENCES gdelt_raw_mentions(id),
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    staged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    global_event_id BIGINT NOT NULL,
    event_time_date TIMESTAMP WITH TIME ZONE,
    mention_time_date TIMESTAMP WITH TIME ZONE,
    mention_type INTEGER,
    mention_source_name TEXT,
    mention_identifier TEXT,
    confidence INTEGER,
    mention_doc_tone DOUBLE PRECISION,
    CONSTRAINT uq_gdelt_stage_mentions_raw UNIQUE (raw_id)
);

CREATE TABLE gdelt_stage_gkg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_id BIGINT NOT NULL REFERENCES gdelt_raw_gkg(id),
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    staged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    gkg_record_id VARCHAR(128) NOT NULL,
    document_date TIMESTAMP WITH TIME ZONE,
    source_collection_identifier INTEGER,
    source_common_name TEXT,
    document_identifier TEXT,
    themes TEXT,
    persons TEXT,
    organizations TEXT,
    locations TEXT,
    tone TEXT,
    CONSTRAINT uq_gdelt_stage_gkg_raw UNIQUE (raw_id)
);

CREATE TABLE gdelt_stage_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_type VARCHAR(16) NOT NULL,
    raw_id BIGINT NOT NULL,
    import_file_id BIGINT NOT NULL REFERENCES gdelt_import_files(id),
    source_file VARCHAR(255) NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    row_number BIGINT NOT NULL,
    raw_tsv TEXT NOT NULL,
    error_code VARCHAR(64) NOT NULL,
    error_message TEXT NOT NULL,
    staged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gdelt_stage_errors_raw UNIQUE (dataset_type, raw_id)
);
