CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_url TEXT NOT NULL,
    url_hash VARCHAR(64) NOT NULL,
    domain TEXT NOT NULL,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_articles_url_hash UNIQUE (url_hash)
);

CREATE INDEX idx_articles_first_seen_at ON articles (first_seen_at);
CREATE INDEX idx_articles_domain ON articles (domain);

CREATE TABLE article_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id),
    signal_type VARCHAR(16) NOT NULL,
    source_id BIGINT NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    global_event_id BIGINT,
    event_code VARCHAR(32),
    themes TEXT,
    persons TEXT,
    organizations TEXT,
    locations TEXT,
    tone_value DOUBLE PRECISION,
    tone_raw TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_article_signals_source UNIQUE (signal_type, source_id)
);

CREATE INDEX idx_article_signals_article_id ON article_signals (article_id);
CREATE INDEX idx_article_signals_source_timestamp ON article_signals (source_timestamp);

CREATE TABLE article_extraction_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_type VARCHAR(16) NOT NULL,
    source_id BIGINT NOT NULL,
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    raw_url TEXT,
    error_code VARCHAR(64) NOT NULL,
    error_message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_article_extraction_errors_source UNIQUE (signal_type, source_id)
);

CREATE INDEX idx_article_extraction_errors_source_timestamp
    ON article_extraction_errors (source_timestamp);
