DROP VIEW article_detail_view;
DROP VIEW article_signal_summary_view;

CREATE TABLE gdelt_gkg_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL REFERENCES articles(id),
    source_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    document_identifier TEXT,
    page_title VARCHAR(1000),
    themes_raw TEXT,
    persons_raw TEXT,
    organizations_raw TEXT,
    locations_raw TEXT,
    tone_raw TEXT,
    tone_value DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gdelt_gkg_records_source UNIQUE (source_id)
);

CREATE INDEX idx_gdelt_gkg_records_article_id ON gdelt_gkg_records (article_id);
CREATE INDEX idx_gdelt_gkg_records_source_timestamp ON gdelt_gkg_records (source_timestamp);

INSERT INTO gdelt_gkg_records
    (source_id, article_id, source_timestamp, document_identifier, page_title,
     themes_raw, persons_raw, organizations_raw, locations_raw, tone_raw, tone_value, created_at)
SELECT signal.source_id, signal.article_id, signal.source_timestamp, stage.document_identifier,
       stage.page_title, signal.themes, signal.persons, signal.organizations, signal.locations,
       signal.tone_raw, signal.tone_value, signal.created_at
FROM article_signals signal
LEFT JOIN gdelt_stage_gkg stage ON stage.id = signal.source_id
WHERE signal.signal_type = 'GKG';

DELETE FROM article_signals WHERE signal_type = 'GKG';

ALTER TABLE articles DROP CONSTRAINT ck_articles_title_source;
ALTER TABLE articles DROP COLUMN title;
ALTER TABLE articles DROP COLUMN title_source;

CREATE VIEW article_signal_summary_view AS
SELECT
    a.id AS article_id,
    a.canonical_url,
    a.domain,
    a.first_seen_at,
    COUNT(all_signals.source_id) AS signal_count,
    SUM(CASE WHEN all_signals.signal_type IN ('EVENT', 'EVENTS') THEN 1 ELSE 0 END) AS event_signal_count,
    SUM(CASE WHEN all_signals.signal_type IN ('MENTION', 'MENTIONS') THEN 1 ELSE 0 END) AS mention_signal_count,
    SUM(CASE WHEN all_signals.signal_type = 'GKG' THEN 1 ELSE 0 END) AS gkg_signal_count,
    MIN(all_signals.source_timestamp) AS earliest_signal_at,
    MAX(all_signals.source_timestamp) AS latest_signal_at
FROM articles a
LEFT JOIN (
    SELECT article_id, signal_type, source_id, source_timestamp FROM article_signals
    UNION ALL
    SELECT article_id, 'GKG', source_id, source_timestamp FROM gdelt_gkg_records
) all_signals ON all_signals.article_id = a.id
GROUP BY a.id, a.canonical_url, a.domain, a.first_seen_at;

CREATE VIEW article_detail_view AS
SELECT
    a.id AS article_id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
    a.created_at AS article_created_at, a.updated_at AS article_updated_at,
    s.id AS signal_id, s.signal_type, s.source_id, s.source_timestamp,
    s.global_event_id, s.event_code, s.themes, s.persons, s.organizations,
    s.locations, s.tone_value, s.tone_raw, s.created_at AS signal_created_at
FROM articles a
JOIN article_signals s ON s.article_id = a.id
UNION ALL
SELECT
    a.id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
    a.created_at, a.updated_at,
    g.id, 'GKG', g.source_id, g.source_timestamp,
    NULL, NULL, g.themes_raw, g.persons_raw, g.organizations_raw,
    g.locations_raw, g.tone_value, g.tone_raw, g.created_at
FROM articles a
JOIN gdelt_gkg_records g ON g.article_id = a.id
UNION ALL
SELECT
    a.id, a.canonical_url, a.url_hash, a.domain, a.first_seen_at,
    a.created_at, a.updated_at,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM articles a
WHERE NOT EXISTS (SELECT 1 FROM article_signals s WHERE s.article_id = a.id)
  AND NOT EXISTS (SELECT 1 FROM gdelt_gkg_records g WHERE g.article_id = a.id);
